
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.Table table1;
	private global::Gtk.Label bonusLabel;
	private global::Gtk.CheckButton ericCheck;
	private global::Gtk.Label ericDescLabel;
	private global::Gtk.Label ericResultLabel;
	private global::Gtk.Label ericRollLabel;
	private global::Gtk.SpinButton ericSpin;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.Label mysteryFluidLabel;
	private global::Gtk.Label nmfDescLabel;
	private global::Gtk.Label nmfRollLabel;
	private global::Gtk.Label resultLabel;
	private global::Gtk.Label resultLabel1;
	private global::Gtk.Button rollButton;
	private global::Gtk.CheckButton stanCheck;
	private global::Gtk.Label stanDescLabel;
	private global::Gtk.Label stanResultLabel;
	private global::Gtk.Label stanRollLabel;
	private global::Gtk.SpinButton stanSpin;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Numerian Mystery Fluid");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(8)), ((uint)(4)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(12));
		// Container child table1.Gtk.Table+TableChild
		this.bonusLabel = new global::Gtk.Label ();
		this.bonusLabel.Name = "bonusLabel";
		this.bonusLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><u>Alchemy Bonus</u></b>");
		this.bonusLabel.UseMarkup = true;
		this.table1.Add (this.bonusLabel);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.bonusLabel]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.ericCheck = new global::Gtk.CheckButton ();
		this.ericCheck.CanFocus = true;
		this.ericCheck.Name = "ericCheck";
		this.ericCheck.Label = global::Mono.Unix.Catalog.GetString ("Beraq-Dul");
		this.ericCheck.Active = true;
		this.ericCheck.DrawIndicator = true;
		this.ericCheck.UseUnderline = true;
		this.table1.Add (this.ericCheck);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.ericCheck]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.ericDescLabel = new global::Gtk.Label ();
		this.ericDescLabel.Name = "ericDescLabel";
		this.ericDescLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("ericDescLabel");
		this.table1.Add (this.ericDescLabel);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.ericDescLabel]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(4));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.ericResultLabel = new global::Gtk.Label ();
		this.ericResultLabel.Name = "ericResultLabel";
		this.ericResultLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("ericResultLabel");
		this.table1.Add (this.ericResultLabel);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.ericResultLabel]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(3));
		w4.RightAttach = ((uint)(4));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.ericRollLabel = new global::Gtk.Label ();
		this.ericRollLabel.Name = "ericRollLabel";
		this.ericRollLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("ericRollLabel");
		this.table1.Add (this.ericRollLabel);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.ericRollLabel]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.ericSpin = new global::Gtk.SpinButton (0, 100, 1);
		this.ericSpin.CanFocus = true;
		this.ericSpin.Name = "ericSpin";
		this.ericSpin.Adjustment.PageIncrement = 10;
		this.ericSpin.ClimbRate = 1;
		this.ericSpin.Numeric = true;
		this.ericSpin.Value = 10;
		this.table1.Add (this.ericSpin);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.ericSpin]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.table1.Add (this.hseparator1);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.hseparator1]));
		w7.TopAttach = ((uint)(5));
		w7.BottomAttach = ((uint)(6));
		w7.RightAttach = ((uint)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.mysteryFluidLabel = new global::Gtk.Label ();
		this.mysteryFluidLabel.Name = "mysteryFluidLabel";
		this.mysteryFluidLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Numerian Mystery Fluid:</b>");
		this.mysteryFluidLabel.UseMarkup = true;
		this.table1.Add (this.mysteryFluidLabel);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.mysteryFluidLabel]));
		w8.TopAttach = ((uint)(6));
		w8.BottomAttach = ((uint)(7));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.nmfDescLabel = new global::Gtk.Label ();
		this.nmfDescLabel.Name = "nmfDescLabel";
		this.nmfDescLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("nmfDescLabel");
		this.table1.Add (this.nmfDescLabel);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.nmfDescLabel]));
		w9.TopAttach = ((uint)(7));
		w9.BottomAttach = ((uint)(8));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(4));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.nmfRollLabel = new global::Gtk.Label ();
		this.nmfRollLabel.Name = "nmfRollLabel";
		this.nmfRollLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("nmfRollLabel");
		this.table1.Add (this.nmfRollLabel);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.nmfRollLabel]));
		w10.TopAttach = ((uint)(6));
		w10.BottomAttach = ((uint)(7));
		w10.LeftAttach = ((uint)(2));
		w10.RightAttach = ((uint)(3));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.resultLabel = new global::Gtk.Label ();
		this.resultLabel.Name = "resultLabel";
		this.resultLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><u>Roll</u></b>");
		this.resultLabel.UseMarkup = true;
		this.table1.Add (this.resultLabel);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.resultLabel]));
		w11.LeftAttach = ((uint)(2));
		w11.RightAttach = ((uint)(3));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.resultLabel1 = new global::Gtk.Label ();
		this.resultLabel1.Name = "resultLabel1";
		this.resultLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><u>Results</u></b>");
		this.resultLabel1.UseMarkup = true;
		this.table1.Add (this.resultLabel1);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.resultLabel1]));
		w12.LeftAttach = ((uint)(3));
		w12.RightAttach = ((uint)(4));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.rollButton = new global::Gtk.Button ();
		this.rollButton.CanFocus = true;
		this.rollButton.Name = "rollButton";
		this.rollButton.UseUnderline = true;
		this.rollButton.Label = global::Mono.Unix.Catalog.GetString ("Roll");
		this.table1.Add (this.rollButton);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.rollButton]));
		w13.TopAttach = ((uint)(6));
		w13.BottomAttach = ((uint)(7));
		w13.LeftAttach = ((uint)(3));
		w13.RightAttach = ((uint)(4));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.stanCheck = new global::Gtk.CheckButton ();
		this.stanCheck.CanFocus = true;
		this.stanCheck.Name = "stanCheck";
		this.stanCheck.Label = global::Mono.Unix.Catalog.GetString ("Tar");
		this.stanCheck.Active = true;
		this.stanCheck.DrawIndicator = true;
		this.stanCheck.UseUnderline = true;
		this.table1.Add (this.stanCheck);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.stanCheck]));
		w14.TopAttach = ((uint)(3));
		w14.BottomAttach = ((uint)(4));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.stanDescLabel = new global::Gtk.Label ();
		this.stanDescLabel.Name = "stanDescLabel";
		this.stanDescLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("stanDescLabel");
		this.table1.Add (this.stanDescLabel);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.stanDescLabel]));
		w15.TopAttach = ((uint)(4));
		w15.BottomAttach = ((uint)(5));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(4));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.stanResultLabel = new global::Gtk.Label ();
		this.stanResultLabel.Name = "stanResultLabel";
		this.stanResultLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"red\">stanResultLabel</span>");
		this.stanResultLabel.UseMarkup = true;
		this.table1.Add (this.stanResultLabel);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.stanResultLabel]));
		w16.TopAttach = ((uint)(3));
		w16.BottomAttach = ((uint)(4));
		w16.LeftAttach = ((uint)(3));
		w16.RightAttach = ((uint)(4));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.stanRollLabel = new global::Gtk.Label ();
		this.stanRollLabel.Name = "stanRollLabel";
		this.stanRollLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("stanRollLabel");
		this.table1.Add (this.stanRollLabel);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.stanRollLabel]));
		w17.TopAttach = ((uint)(3));
		w17.BottomAttach = ((uint)(4));
		w17.LeftAttach = ((uint)(2));
		w17.RightAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.stanSpin = new global::Gtk.SpinButton (0, 100, 1);
		this.stanSpin.CanFocus = true;
		this.stanSpin.Name = "stanSpin";
		this.stanSpin.Adjustment.PageIncrement = 10;
		this.stanSpin.ClimbRate = 1;
		this.stanSpin.Numeric = true;
		this.stanSpin.Value = 11;
		this.table1.Add (this.stanSpin);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.stanSpin]));
		w18.TopAttach = ((uint)(3));
		w18.BottomAttach = ((uint)(4));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add (this.table1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 407;
		this.DefaultHeight = 235;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.rollButton.Clicked += new global::System.EventHandler (this.OnRollButtonClicked);
	}
}
